# Generated by Django 6.0.5 on 2026-05-11 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerDecisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(help_text='Brief description of the critical issue', max_length=300)),
                ('impact', models.TextField(help_text='Impact on schedule, cost, or safety if unresolved')),
                ('decision_required', models.TextField(help_text='Specific decision or action needed from owner')),
                ('responsible_party', models.CharField(help_text='Person or team responsible', max_length=200)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Decided', 'Decided'), ('Escalated', 'Escalated')], default='Pending', max_length=20)),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium')], default='High', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_decisions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_decisions', to='projects.project')),
            ],
            options={
                'verbose_name': 'Owner Decision Item',
                'verbose_name_plural': 'Owner Decision Items',
                'ordering': [models.Case(models.When(priority='Critical', then=0), models.When(priority='High', then=1), models.When(priority='Medium', then=2), default=3, output_field=models.IntegerField()), 'due_date'],
            },
        ),
    ]
