# Generated by Django 6.0.5 on 2026-05-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('project_manager', 'Project Manager'), ('engineer', 'Engineer'), ('inspector', 'Inspector'), ('contractor', 'Contractor'), ('owner', 'Owner'), ('site_engineer', 'Site Engineer'), ('quantity_surveyor', 'Quantity Surveyor'), ('safety_officer', 'Safety Officer'), ('storekeeper', 'Storekeeper'), ('viewer', 'Viewer')], default='viewer', max_length=30),
        ),
    ]
