# Generated by Django 6.0.5 on 2026-05-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_engineer_inspector_contractor_owner_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('project_manager', 'Project Manager'), ('construction_manager', 'Construction Manager'), ('office_engineer', 'Office Engineer'), ('engineer', 'Engineer'), ('site_engineer', 'Site Engineer'), ('inspector', 'Inspector'), ('quantity_surveyor', 'Quantity Surveyor'), ('safety_officer', 'Safety Officer'), ('document_controller', 'Document Controller'), ('project_coordinator', 'Project Coordinator'), ('legal_officer', 'Legal Officer'), ('environmental_specialist', 'Environmental Specialist'), ('senior_advisor', 'Senior Advisor'), ('contractor', 'Contractor'), ('owner', 'Owner'), ('storekeeper', 'Storekeeper'), ('viewer', 'Viewer')], default='viewer', max_length=30),
        ),
    ]
