# Generated by Django 6.0.5 on 2026-05-24 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_materialdelivery_source_area'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdelivery',
            name='delivery_image',
            field=models.ImageField(blank=True, null=True, upload_to='deliveries/%Y/%m/', verbose_name='รูปตั๋ว/ใบส่งของ'),
        ),
        migrations.AlterField(
            model_name='materialdelivery',
            name='delivery_date',
            field=models.DateField(verbose_name='วันที่รับวัสดุ'),
        ),
        migrations.AlterField(
            model_name='materialdelivery',
            name='delivery_note_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='เลขที่ใบส่งของ'),
        ),
        migrations.AlterField(
            model_name='materialdelivery',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_deliveries', to='projects.workarea', verbose_name='ปลายทาง (กอง/พื้นที่)'),
        ),
        migrations.AlterField(
            model_name='materialdelivery',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material', verbose_name='วัสดุ'),
        ),
        migrations.AlterField(
            model_name='materialdelivery',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='ปริมาณ'),
        ),
        migrations.AlterField(
            model_name='materialdelivery',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='materialdelivery',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='แหล่งวัสดุ (ข้อความ)'),
        ),
        migrations.AlterField(
            model_name='materialdelivery',
            name='truck_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='ทะเบียนรถ'),
        ),
        migrations.AlterField(
            model_name='materialdelivery',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='ราคาต่อหน่วย'),
        ),
    ]
