# Generated by Django 6.0.5 on 2026-05-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_materialdelivery_delivery_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdelivery',
            name='ocr_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='OCR confidence'),
        ),
        migrations.AddField(
            model_name='materialdelivery',
            name='ocr_processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OCR processed at'),
        ),
        migrations.AddField(
            model_name='materialdelivery',
            name='ocr_raw_text',
            field=models.TextField(blank=True, default='', verbose_name='OCR raw text'),
        ),
        migrations.AddField(
            model_name='materialdelivery',
            name='ocr_template',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='OCR template'),
        ),
    ]
