# Generated by Django 6.0.5 on 2026-05-11 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controls', '0003_sand_source'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='import_type',
            field=models.CharField(choices=[('rock_summary', 'Rock Summary'), ('sand_summary', 'Sand Summary'), ('recovery_action_plan', 'Recovery Action Plan'), ('revetment_progress', 'Revetment Progress')], max_length=30),
        ),
        migrations.CreateModel(
            name='RevetmentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('template_column', models.CharField(blank=True, max_length=5)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('is_inspection', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revetment_activities', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', 'group_name', 'name'],
                'unique_together': {('project', 'group_name', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RevetmentDailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('day_name', models.CharField(blank=True, max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revetment_records_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revetment_daily_records', to='projects.project')),
            ],
            options={
                'ordering': ['-record_date'],
                'unique_together': {('project', 'record_date')},
            },
        ),
        migrations.CreateModel(
            name='RevetmentStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop', models.CharField(blank=True, max_length=50)),
                ('station', models.CharField(max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revetment_stations', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', 'station'],
                'unique_together': {('project', 'station')},
            },
        ),
        migrations.CreateModel(
            name='RevetmentDailyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_done', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('status', models.CharField(blank=True, choices=[('Opening', 'Opening'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished'), ('Inspected', 'Inspected'), ('No Activity', 'No Activity')], max_length=20)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_items', to='project_controls.revetmentactivity')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='project_controls.revetmentdailyrecord')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_items', to='project_controls.revetmentstation')),
            ],
            options={
                'ordering': ['station__sort_order', 'activity__sort_order'],
                'unique_together': {('record', 'station', 'activity')},
            },
        ),
    ]
