# Generated by Django 6.0.5 on 2026-05-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_controls', '0004_alter_importlog_import_type_revetmentactivity_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='revetmentactivity',
            unique_together={('project', 'template_column', 'name')},
        ),
    ]
