# Generated by Django 6.0.5 on 2026-05-12 01:17

from django.db import migrations, models


def backfill_khlong_bang_phai_from_legacy_oswald(apps, schema_editor):
    SandDailyRecord = apps.get_model('project_controls', 'SandDailyRecord')
    project_ids = SandDailyRecord.objects.values_list('project_id', flat=True).distinct()
    for project_id in project_ids:
        total_accum = 0
        khlong_accum = 0
        for record in SandDailyRecord.objects.filter(project_id=project_id).order_by('record_date', 'pk'):
            record.khlong_bang_phai_daily_ton = record.oswald_daily_ton
            khlong_accum += record.khlong_bang_phai_daily_ton
            record.khlong_bang_phai_accum_ton = khlong_accum
            record.khlong_bang_phai_trips = record.oswald_trips
            record.khlong_bang_phai_trucks = record.oswald_trucks
            record.total_daily_ton = record.tct_daily_ton + record.mtp3_daily_ton
            total_accum += record.total_daily_ton
            record.total_accum_ton = total_accum
            if record.sand_source in ('', 'Oswald'):
                record.sand_source = 'Khlong Bang Phai (Oswald)'
            record.save(update_fields=[
                'khlong_bang_phai_daily_ton',
                'khlong_bang_phai_accum_ton',
                'khlong_bang_phai_trips',
                'khlong_bang_phai_trucks',
                'total_daily_ton',
                'total_accum_ton',
                'sand_source',
            ])


class Migration(migrations.Migration):

    dependencies = [
        ('project_controls', '0005_alter_revetmentactivity_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanddailyrecord',
            name='chalothon_accum_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sanddailyrecord',
            name='chalothon_daily_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sanddailyrecord',
            name='chalothon_trips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sanddailyrecord',
            name='chalothon_trucks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sanddailyrecord',
            name='khlong_bang_phai_accum_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sanddailyrecord',
            name='khlong_bang_phai_daily_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sanddailyrecord',
            name='khlong_bang_phai_trips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sanddailyrecord',
            name='khlong_bang_phai_trucks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sanddailyrecord',
            name='sand_source',
            field=models.CharField(blank=True, default='Khlong Bang Phai (Oswald)', max_length=200),
        ),
        migrations.RunPython(backfill_khlong_bang_phai_from_legacy_oswald, migrations.RunPython.noop),
    ]
