# Generated by Django 6.0.5 on 2026-05-12 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controls', '0006_sanddailyrecord_chalothon_accum_ton_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockdailyrecord',
            name='destination_area',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rockdailyrecord',
            name='material_type',
            field=models.CharField(blank=True, choices=[('Core Rock', 'Core Rock'), ('Bedding Rock', 'Bedding Rock'), ('Armour Rock', 'Armour Rock'), ('Toe Rock', 'Toe Rock'), ('Quarry Run', 'Quarry Run')], max_length=30),
        ),
        migrations.AddField(
            model_name='rockdailyrecord',
            name='source_quarry',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rockbargeplacement',
            name='trips',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RockDashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_quantity_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('daily_target_placement_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_finish_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rock_dashboard_settings', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Rock Dashboard Settings',
            },
        ),
        migrations.CreateModel(
            name='RockStationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_range', models.CharField(max_length=100)),
                ('material_type', models.CharField(choices=[('Core Rock', 'Core Rock'), ('Bedding Rock', 'Bedding Rock'), ('Armour Rock', 'Armour Rock'), ('Toe Rock', 'Toe Rock'), ('Quarry Run', 'Quarry Run')], default='Core Rock', max_length=30)),
                ('delivered_quantity_ton', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('placed_quantity_ton', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_quantity_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rock_station_progress', to='projects.project')),
            ],
            options={
                'ordering': ['station_range', 'material_type'],
                'unique_together': {('project', 'station_range', 'material_type')},
            },
        ),
    ]
