# Generated by Django 6.0.5 on 2026-05-12 02:06

import django.db.models.deletion
from django.db import migrations, models


def mark_missing_sand_barge_trip_data(apps, schema_editor):
    SandBargePlacement = apps.get_model('project_controls', 'SandBargePlacement')
    SandBargePlacement.objects.filter(quantity_ton__gt=0, trips=0).update(
        trips=None,
        destination='Offshore Placement',
        material_type='Sand',
        status='Trip Data Missing',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('project_controls', '0007_rockdailyrecord_destination_area_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandbargeplacement',
            name='destination',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sandbargeplacement',
            name='material_type',
            field=models.CharField(blank=True, default='Sand', max_length=50),
        ),
        migrations.AddField(
            model_name='sandbargeplacement',
            name='placement_type',
            field=models.CharField(choices=[('Offshore', 'Offshore'), ('Onshore', 'Onshore')], default='Offshore', max_length=20),
        ),
        migrations.AddField(
            model_name='sandbargeplacement',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sandbargeplacement',
            name='status',
            field=models.CharField(choices=[('Recorded', 'Recorded'), ('Trip Data Missing', 'Trip Data Missing')], default='Recorded', max_length=30),
        ),
        migrations.AlterField(
            model_name='sandbargeplacement',
            name='trips',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(mark_missing_sand_barge_trip_data, migrations.RunPython.noop),
        migrations.CreateModel(
            name='SandDashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_quantity_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('daily_target_delivery_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('daily_target_placement_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_finish_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sand_dashboard_settings', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Sand Dashboard Settings',
            },
        ),
        migrations.CreateModel(
            name='SandAreaProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_zone', models.CharField(max_length=120)),
                ('planned_quantity_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('delivered_quantity_ton', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('placed_quantity_ton', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('planned_placed_to_date_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('placement_type', models.CharField(blank=True, choices=[('Offshore', 'Offshore'), ('Onshore', 'Onshore')], max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sand_area_progress', to='projects.project')),
            ],
            options={
                'ordering': ['area_zone', 'placement_type'],
                'unique_together': {('project', 'area_zone', 'placement_type')},
            },
        ),
    ]
