# Generated by Django 6.0.5 on 2026-05-12 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controls', '0008_sandbargeplacement_destination_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='revetmentdailyrecord',
            index=models.Index(fields=['project', '-record_date'], name='revetment_project_date_idx'),
        ),
        migrations.AddIndex(
            model_name='rockdailyrecord',
            index=models.Index(fields=['project', '-record_date'], name='rock_project_date_idx'),
        ),
        migrations.AddIndex(
            model_name='sanddailyrecord',
            index=models.Index(fields=['project', '-record_date'], name='sand_project_date_idx'),
        ),
    ]
