# Generated by Django 6.0.5 on 2026-05-12 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controls', '0009_add_dashboard_indexes'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Issue', 'Issue'), ('Risk', 'Risk'), ('Decision', 'Decision'), ('Coordination', 'Coordination'), ('Change', 'Change'), ('Other', 'Other')], default='Issue', max_length=30)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Waiting', 'Waiting'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Open', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=150)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('impact', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_action_plans_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_action_plans', to='projects.project')),
            ],
            options={
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=500)),
                ('responsible_party', models.CharField(blank=True, max_length=150)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Waiting', 'Waiting'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='project_controls.projectactionplan')),
            ],
            options={
                'ordering': ['item_no', 'target_date', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='projectactionplan',
            index=models.Index(fields=['project', 'status', 'due_date'], name='pm_ap_project_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectactionitem',
            unique_together={('action_plan', 'item_no')},
        ),
    ]
