# Generated by Django 6.0.5 on 2026-05-14 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_photos_and_barge_equipment_link'),
        ('project_controls', '0012_transport_units_and_rock_placement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='barge',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='Link to Equipment record (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_units', to='equipment.equipment'),
        ),
    ]
