# Generated by Django 6.0.5 on 2026-05-11 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('weather_morning', models.CharField(choices=[('Sunny', 'Sunny'), ('Partly Cloudy', 'Partly Cloudy'), ('Cloudy', 'Cloudy'), ('Rainy', 'Rainy'), ('Heavy Rain', 'Heavy Rain'), ('Stormy', 'Stormy')], default='Sunny', max_length=30)),
                ('weather_afternoon', models.CharField(choices=[('Sunny', 'Sunny'), ('Partly Cloudy', 'Partly Cloudy'), ('Cloudy', 'Cloudy'), ('Rainy', 'Rainy'), ('Heavy Rain', 'Heavy Rain'), ('Stormy', 'Stormy')], default='Sunny', max_length=30)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_reports', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='projects.project')),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('project', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyProblemRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Weather', 'Weather'), ('Labour', 'Labour'), ('Equipment', 'Equipment'), ('Material', 'Material'), ('Design', 'Design'), ('Safety', 'Safety'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('impact', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='daily_reports.dailyreport')),
            ],
        ),
        migrations.CreateModel(
            name='DailyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='daily_reports/%Y/%m/%d/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='daily_reports.dailyreport')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLookahead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_activity', models.CharField(max_length=500)),
                ('planned_date', models.DateField()),
                ('responsible_person', models.CharField(max_length=200)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookaheads', to='daily_reports.dailyreport')),
            ],
        ),
        migrations.CreateModel(
            name='DailyWorkActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('percent_complete', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='daily_reports.dailyreport')),
                ('work_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.workarea')),
            ],
        ),
    ]
