# Generated by Django 6.0.5 on 2026-05-12 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('contractor_name', models.CharField(max_length=200)),
                ('weather_day', models.CharField(choices=[('Clear', 'Clear'), ('Cloudy', 'Cloudy'), ('Windy', 'Windy'), ('Raining', 'Raining'), ('High Wave', 'High Wave'), ('Other', 'Other')], default='Clear', max_length=20)),
                ('weather_night', models.CharField(choices=[('Clear', 'Clear'), ('Cloudy', 'Cloudy'), ('Windy', 'Windy'), ('Raining', 'Raining'), ('High Wave', 'High Wave'), ('Other', 'Other')], default='Clear', max_length=20)),
                ('wind_speed', models.CharField(blank=True, max_length=50)),
                ('total_manpower', models.PositiveIntegerField(default=0)),
                ('prepared_by_name', models.CharField(blank=True, max_length=200)),
                ('checked_by_name', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Imported', 'Imported to Daily Report'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='contractor_imports/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('daily_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_imports', to='daily_reports.dailyreport')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_imports', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractorImportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('problem', models.CharField(blank=True, max_length=300)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('contractor_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='daily_reports.contractorimport')),
            ],
            options={
                'ordering': ['item_no'],
            },
        ),
        migrations.CreateModel(
            name='ContractorImportEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('contractor_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='daily_reports.contractorimport')),
            ],
            options={
                'ordering': ['equipment_name'],
            },
        ),
        migrations.CreateModel(
            name='ContractorImportLookahead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('contractor_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookaheads', to='daily_reports.contractorimport')),
            ],
            options={
                'ordering': ['item_no'],
            },
        ),
        migrations.CreateModel(
            name='ContractorImportManpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('contractor_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpower_items', to='daily_reports.contractorimport')),
            ],
            options={
                'ordering': ['role'],
            },
        ),
    ]
