# Generated by Django 6.0.5 on 2026-05-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0002_contractorimport_contractorimportactivity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyphoto',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='dailyphoto',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
