# Generated by Django 6.0.5 on 2026-05-21 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('registration_no', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('Civil', 'Civil Works'), ('MEP', 'MEP'), ('Steel', 'Steel Structure'), ('Concrete', 'Concrete Works'), ('Piling', 'Piling'), ('Marine', 'Marine Works'), ('Earthworks', 'Earthworks'), ('Survey', 'Survey'), ('Dredging', 'Dredging'), ('Other', 'Other')], default='Other', max_length=30)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blacklisted', 'Blacklisted')], default='Active', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('bank_account', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractorContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('contract_type', models.CharField(choices=[('LumpSum', 'Lump Sum'), ('UnitRate', 'Unit Rate'), ('CostPlus', 'Cost Plus'), ('TimeAndMaterial', 'Time & Material')], default='LumpSum', max_length=20)),
                ('scope_of_work', models.TextField(blank=True)),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('retention_pct', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Suspended', 'Suspended'), ('Completed', 'Completed'), ('Terminated', 'Terminated')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontracts_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontracts', to='projects.project')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='subcontractors.subcontractor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_no', models.CharField(blank=True, max_length=20)),
                ('claim_date', models.DateField()),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('certified_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('retention_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Certified', 'Certified'), ('Paid', 'Paid'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('certified_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certified_claims', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_claims', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_claims', to='subcontractors.subcontractorcontract')),
            ],
            options={
                'ordering': ['-claim_date'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractorWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('contract_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('completed_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='subcontractors.subcontractorcontract')),
            ],
        ),
    ]
