# Generated by Django 6.0.5 on 2026-05-11 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('unit', models.CharField(max_length=50)),
                ('contract_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='projects.project')),
            ],
            options={
                'ordering': ['item_no'],
                'unique_together': {('project', 'item_no')},
            },
        ),
        migrations.CreateModel(
            name='DailyProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('daily_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('allow_overrun', models.BooleanField(default=False)),
                ('boq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='boq.boqitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='projects.project')),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_no', models.CharField(max_length=30)),
                ('claim_date', models.DateField()),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('total_claimed_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Certified', 'Certified'), ('Paid', 'Paid')], default='Draft', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_claims', to='projects.project')),
            ],
            options={
                'ordering': ['-claim_date'],
                'unique_together': {('project', 'claim_no')},
            },
        ),
    ]
