# Generated by Django 6.0.5 on 2026-06-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
