# Generated by Django 6.0.5 on 2026-06-06 06:52

import django.db.models.deletion
from django.db import migrations, models


def populate_sort_keys(apps, schema_editor):
    BOQItem = apps.get_model('boq', 'BOQItem')
    for item in BOQItem.objects.all():
        parts = item.item_no.split('.')
        try:
            sort_key = '.'.join(str(int(p)).zfill(6) for p in parts)
        except (ValueError, AttributeError):
            sort_key = item.item_no
        BOQItem.objects.filter(pk=item.pk).update(sort_key=sort_key)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0002_boqitem_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boqitem',
            options={'ordering': ['sort_key']},
        ),
        migrations.RemoveField(
            model_name='boqitem',
            name='category',
        ),
        migrations.AddField(
            model_name='boqitem',
            name='item_type',
            field=models.CharField(choices=[('header', 'Section Header'), ('item', 'Line Item')], default='item', max_length=10),
        ),
        migrations.AddField(
            model_name='boqitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='boq.boqitem'),
        ),
        migrations.AddField(
            model_name='boqitem',
            name='sort_key',
            field=models.CharField(db_index=True, default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='contract_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='unit_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.RunPython(populate_sort_keys, noop),
    ]
