# Generated by Django 6.0.5 on 2026-05-11 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daily_reports', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Engineer', 'Engineer'), ('Foreman', 'Foreman'), ('Surveyor', 'Surveyor'), ('SafetyOfficer', 'Safety Officer'), ('Operator', 'Operator'), ('Driver', 'Driver'), ('GeneralWorker', 'General Worker'), ('Other', 'Other')], max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Manpower Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyManpowerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('company', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpower_records', to='projects.project')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manpower_records', to='daily_reports.dailyreport')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manpower.manpowercategory')),
            ],
            options={
                'ordering': ['-report_date', 'category'],
            },
        ),
    ]
