# Generated by Django 6.0.5 on 2026-06-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymanpowerrecord',
            options={'ordering': ['-report_date', 'category__sort_order']},
        ),
        migrations.AlterModelOptions(
            name='manpowercategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Manpower Categories'},
        ),
        migrations.RemoveField(
            model_name='manpowercategory',
            name='description',
        ),
        migrations.AddField(
            model_name='manpowercategory',
            name='name_th',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='manpowercategory',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manpowercategory',
            name='name',
            field=models.CharField(choices=[('CivilEngineer', 'Civil Engineer (CE)'), ('MechanicalEngineer', 'Mechanical Engineer (ME)'), ('ElectricalEngineer', 'Electrical Engineer (EE)'), ('Foreman', 'Foreman / Supervisor'), ('Technician', 'Technician / QC Inspector'), ('SafetyOfficer', 'Safety Officer (จ.ป.)'), ('Headman', 'Headman / Gang Leader'), ('Carpenter', 'Carpenter'), ('Mason', 'Mason'), ('SteelWorker', 'Steel Worker'), ('Fitter', 'Fitter / Assistant'), ('Welder', 'Welder'), ('Electrician', 'Electrician'), ('Surveyor', 'Surveyor'), ('EquipmentOperator', 'Equipment Operator'), ('GeneralWorker', 'General Worker / Laborer'), ('Driver', 'Driver'), ('Mechanic', 'Mechanic (MC)')], max_length=50, unique=True),
        ),
    ]
