# Generated by Django 6.0.5 on 2026-05-11 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('NearMiss', 'Near Miss'), ('FirstAid', 'First Aid'), ('MedicalTreatment', 'Medical Treatment'), ('LostTime', 'Lost Time'), ('Fatal', 'Fatal')], max_length=20)),
                ('description', models.TextField()),
                ('injured_person', models.CharField(blank=True, max_length=200)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Closed', 'Closed')], default='Draft', max_length=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='projects.project')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='JSEARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_activity', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('work_area', models.CharField(max_length=200)),
                ('attachment', models.FileField(blank=True, upload_to='safety/jsea/%Y/%m/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jsea_approved', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jsea_prepared', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jsea_records', to='projects.project')),
            ],
            options={
                'verbose_name': 'JSEA Record',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SafetyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('finding', models.TextField()),
                ('action_required', models.TextField()),
                ('responsible_person', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('InProgress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=15)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, upload_to='safety/inspections/%Y/%m/')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_inspections', to='projects.project')),
            ],
            options={
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='ToolboxMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('topic', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=200)),
                ('attendee_count', models.PositiveIntegerField(default=0)),
                ('attachment', models.FileField(blank=True, upload_to='safety/toolbox/%Y/%m/')),
                ('remarks', models.TextField(blank=True)),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_meetings', to='projects.project')),
            ],
            options={
                'ordering': ['-meeting_date'],
            },
        ),
    ]
