# Generated by Django 6.0.5 on 2026-05-21 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_no', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('discipline', models.CharField(choices=[('Civil', 'Civil'), ('Structural', 'Structural'), ('Architectural', 'Architectural'), ('MEP', 'MEP'), ('Marine', 'Marine'), ('Geotechnical', 'Geotechnical'), ('Survey', 'Survey'), ('Landscape', 'Landscape'), ('Other', 'Other')], default='Civil', max_length=30)),
                ('revision', models.CharField(default='A', max_length=10)),
                ('status', models.CharField(choices=[('IFR', 'Issued for Review'), ('IFA', 'Issued for Approval'), ('IFC', 'Issued for Construction'), ('IFT', 'Issued for Tender'), ('AFC', 'Approved for Construction'), ('AsBuilt', 'As-Built'), ('Superseded', 'Superseded'), ('Cancelled', 'Cancelled')], default='IFR', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('prepared_by', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='drawings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawings_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='projects.project')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='drawings.drawing')),
            ],
            options={
                'ordering': ['drawing_no', 'revision'],
                'unique_together': {('project', 'drawing_no', 'revision')},
            },
        ),
        migrations.CreateModel(
            name='RFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfi_no', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Critical', 'Critical')], default='Normal', max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Submitted', 'Submitted'), ('UnderReview', 'Under Review'), ('Answered', 'Answered'), ('Closed', 'Closed'), ('Void', 'Void')], default='Open', max_length=20)),
                ('submitted_by', models.CharField(blank=True, max_length=200)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('response_required_date', models.DateField(blank=True, null=True)),
                ('answer', models.TextField(blank=True)),
                ('answered_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, upload_to='rfi_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfis_answered', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfis_created', to=settings.AUTH_USER_MODEL)),
                ('drawing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfis', to='drawings.drawing')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfis', to='projects.project')),
            ],
            options={
                'verbose_name': 'RFI',
                'ordering': ['-created_at'],
            },
        ),
    ]
