# Generated by Django 6.0.5 on 2026-05-21 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_equipment_photos_and_barge_equipment_link'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('work_type', models.CharField(choices=[('Preventive', 'Preventive Maintenance (PM)'), ('Inspection', 'Periodic Inspection'), ('Overhaul', 'Overhaul / Major Service'), ('Calibration', 'Calibration'), ('Other', 'Other')], default='Preventive', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('interval_type', models.CharField(choices=[('Hours', 'Every X Running Hours'), ('Days', 'Every X Days'), ('Weeks', 'Every X Weeks'), ('Months', 'Every X Months')], default='Hours', max_length=10)),
                ('interval_value', models.PositiveIntegerField(help_text='Repeat every N hours/days/weeks/months')),
                ('last_done_date', models.DateField(blank=True, null=True)),
                ('last_done_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Running hours at last service', max_digits=10, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('next_due_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='equipment.equipment')),
            ],
            options={
                'ordering': ['equipment__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('work_type', models.CharField(choices=[('Preventive', 'Preventive (Scheduled)'), ('Corrective', 'Corrective (Breakdown)'), ('Emergency', 'Emergency'), ('Inspection', 'Periodic Inspection'), ('Overhaul', 'Overhaul')], max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('InProgress', 'In Progress'), ('OnHold', 'On Hold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Open', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('planned_date', models.DateField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('running_hours_at_service', models.DecimalField(blank=True, decimal_places=2, help_text='Equipment running hours when service was done', max_digits=10, null=True)),
                ('assigned_to', models.CharField(blank=True, help_text='Technician / workshop name', max_length=200)),
                ('findings', models.TextField(blank=True, help_text='What was found during inspection/repair')),
                ('actions_taken', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('next_service_due_date', models.DateField(blank=True, null=True)),
                ('next_service_due_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_wo', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wo', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='equipment.equipment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_orders', to='projects.project')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.maintenanceschedule')),
            ],
            options={
                'ordering': ['-planned_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200)),
                ('part_no', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='maintenance.maintenanceworkorder')),
            ],
            options={
                'ordering': ['part_name'],
            },
        ),
    ]
