# Generated by Django 6.0.5 on 2026-05-11 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boq', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_package', models.CharField(blank=True, max_length=200)),
                ('inspection_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('station_or_chainage', models.CharField(blank=True, max_length=100)),
                ('inspection_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Draft', max_length=20)),
                ('result', models.CharField(choices=[('Pending', 'Pending'), ('Pass', 'Pass'), ('Fail', 'Fail'), ('Conditional', 'Conditional')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='boq.boqitem')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_quality_inspections', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_inspections', to='projects.project')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_quality_inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inspection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NonConformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncr_no', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('preventive_action', models.TextField(blank=True)),
                ('issued_date', models.DateField()),
                ('due_date', models.DateField()),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Open', max_length=20)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('boq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_conformances', to='boq.boqitem')),
                ('inspection_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_conformances', to='quality.inspectionrequest')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_conformances', to='projects.project')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_non_conformances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PunchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('target_date', models.DateField()),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_list_items', to='projects.project')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_punch_list_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_name', models.CharField(max_length=200)),
                ('specification_ref', models.CharField(blank=True, max_length=200)),
                ('acceptance_criteria', models.TextField()),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('boq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checkpoints', to='boq.boqitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checkpoints', to='projects.project')),
            ],
            options={
                'ordering': ['project__contract_no', 'checkpoint_name'],
            },
        ),
        migrations.AddIndex(
            model_name='inspectionrequest',
            index=models.Index(fields=['project'], name='quality_ir_project_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrequest',
            index=models.Index(fields=['status'], name='quality_ir_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrequest',
            index=models.Index(fields=['inspection_date'], name='quality_ir_date_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrequest',
            index=models.Index(fields=['project', 'status'], name='quality_ir_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='nonconformance',
            index=models.Index(fields=['project'], name='quality_ncr_project_idx'),
        ),
        migrations.AddIndex(
            model_name='nonconformance',
            index=models.Index(fields=['status'], name='quality_ncr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='nonconformance',
            index=models.Index(fields=['due_date'], name='quality_ncr_due_idx'),
        ),
        migrations.AddIndex(
            model_name='nonconformance',
            index=models.Index(fields=['project', 'status'], name='quality_ncr_proj_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nonconformance',
            unique_together={('project', 'ncr_no')},
        ),
        migrations.AddIndex(
            model_name='punchlist',
            index=models.Index(fields=['project'], name='quality_pl_project_idx'),
        ),
        migrations.AddIndex(
            model_name='punchlist',
            index=models.Index(fields=['status'], name='quality_pl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='punchlist',
            index=models.Index(fields=['target_date'], name='quality_pl_target_idx'),
        ),
        migrations.AddIndex(
            model_name='punchlist',
            index=models.Index(fields=['project', 'status'], name='quality_pl_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycheckpoint',
            index=models.Index(fields=['project'], name='quality_cp_project_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycheckpoint',
            index=models.Index(fields=['is_active'], name='quality_cp_active_idx'),
        ),
    ]
