# Generated by Django 6.0.5 on 2026-05-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformance',
            name='attachment',
            field=models.FileField(blank=True, upload_to='quality/ncr/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='punchlist',
            name='attachment',
            field=models.FileField(blank=True, upload_to='quality/punch-list/%Y/%m/'),
        ),
    ]
