# Generated by Django 6.0.5 on 2026-05-21 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boq', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_no', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Addition', 'Addition — New Scope'), ('Omission', 'Omission — Scope Removed'), ('Substitution', 'Substitution — Scope Replaced'), ('Extension', 'Extension — Time Extension'), ('Acceleration', 'Acceleration — Time Reduction'), ('Other', 'Other')], max_length=20)),
                ('initiated_by', models.CharField(choices=[('Owner', 'Owner'), ('Contractor', 'Contractor'), ('PMC', 'PMC / Consultant'), ('Engineer', 'Engineer')], max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('UnderReview', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('contract_value_impact', models.DecimalField(decimal_places=2, default=0, help_text='Positive = increase, Negative = decrease (THB)', max_digits=15)),
                ('time_impact_days', models.IntegerField(default=0, help_text='Positive = extension, Negative = acceleration (days)')),
                ('initiated_date', models.DateField()),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='change_orders/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_change_orders', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_change_orders', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_orders', to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_change_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiated_date', 'co_no'],
                'unique_together': {('project', 'co_no')},
            },
        ),
        migrations.CreateModel(
            name='ChangeOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('unit', models.CharField(max_length=50)),
                ('change_type', models.CharField(choices=[('Add', 'Add New Item'), ('Modify', 'Modify Quantity'), ('Delete', 'Delete Item')], default='Modify', max_length=10)),
                ('original_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('revised_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('boq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_items', to='boq.boqitem')),
                ('change_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='change_orders.changeorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
