# Generated by Django 6.0.5 on 2026-05-11 13:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boq', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_codes', to='projects.project')),
            ],
            options={
                'verbose_name': 'Cost Code',
                'verbose_name_plural': 'Cost Codes',
                'ordering': ['project', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('committed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='boq.boqitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='projects.project')),
                ('cost_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='cost_control.costcode')),
            ],
            options={
                'verbose_name': 'Budget Item',
                'verbose_name_plural': 'Budget Items',
                'ordering': ['project', 'cost_code__code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='ActualCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('source_type', models.CharField(choices=[('Material', 'Material'), ('Labor', 'Labor'), ('Equipment', 'Equipment'), ('Subcontract', 'Subcontract'), ('Overhead', 'Overhead'), ('Other', 'Other')], default='Other', max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_costs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_costs', to='projects.project')),
                ('cost_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actual_costs', to='cost_control.costcode')),
            ],
            options={
                'verbose_name': 'Actual Cost',
                'verbose_name_plural': 'Actual Costs',
                'ordering': ['-cost_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='costcode',
            index=models.Index(fields=['project', 'is_active'], name='cost_contro_project_5ffbf3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costcode',
            unique_together={('project', 'code')},
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['project', 'cost_code'], name='cost_contro_project_817868_idx'),
        ),
        migrations.AddIndex(
            model_name='actualcost',
            index=models.Index(fields=['project', 'cost_date'], name='cost_contro_project_9fd73a_idx'),
        ),
        migrations.AddIndex(
            model_name='actualcost',
            index=models.Index(fields=['project', 'cost_code'], name='cost_contro_project_d766d9_idx'),
        ),
        migrations.AddIndex(
            model_name='actualcost',
            index=models.Index(fields=['source_type'], name='cost_contro_source__102241_idx'),
        ),
    ]
