# Generated by Django 6.0.5 on 2026-05-21 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('maintenance_overdue', 'Maintenance WO Overdue'), ('maintenance_due_soon', 'PM Due Soon'), ('rfi_overdue', 'RFI Overdue'), ('rfi_answered', 'RFI Answered'), ('leave_pending', 'Leave Pending Approval'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('ot_pending', 'OT Pending Approval'), ('claim_pending', 'Payment Claim Pending'), ('claim_certified', 'Payment Claim Certified'), ('claim_paid', 'Payment Claim Paid'), ('co_pending', 'Change Order Pending'), ('co_approved', 'Change Order Approved'), ('co_rejected', 'Change Order Rejected'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
